version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/validate-terraform-workflow"
    schedule:
      # Check for updates to Terraform every week
      interval: "weekly"      