name: "Engine - Deploy ECS"

on:
  workflow_call:
    inputs:
      cluster-name:
        required: true
        type: string
      service-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      aws-region:
        required: false
        type: string
        default: "us-east-1"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  
jobs:
  deploy-ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.aws-region }}

      - name: Update ECS Service
        run: |
          echo "Atualizando ECS Service ${{ inputs.service-name }} com tag ${{ inputs.image-tag }}"
          aws ecs update-service \
            --cluster ${{ inputs.cluster-name }} \
            --service ${{ inputs.service-name }} \
            --force-new-deployment