name: "Engine - Deploy EKS"

on:
  workflow_call:
    inputs:
      cluster-name:
        required: true
        type: string
      namespace:
        required: false
        type: string
        default: "default"
      deployment-name:
        required: true
        type: string
      container-name:
        required: true
        type: string
      image-uri:
        required: true
        type: string
      aws-region:
        required: false
        type: string
        default: "us-east-1"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  
jobs:
  deploy-eks:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.aws-region }}

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ inputs.cluster-name }} --region ${{ inputs.aws-region }}

      - name: Deploy Image to EKS Deployment
        run: |
          kubectl set image deployment/${{ inputs.deployment-name }} \
            ${{ inputs.container-name }}=${{ inputs.image-uri }} \
            -n ${{ inputs.namespace }}
          kubectl rollout status deployment/${{ inputs.deployment-name }} \
            -n ${{ inputs.namespace }} \
            --timeout=180s