name: "Engine - AWS OIDC Auth"

on:
  workflow_call:
    inputs:
      aws-region:
        required: false
        type: string
        default: "us-east-1"
    secrets:
      aws-role-arn:
        required: true

jobs:
  auth:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.aws-region }}
          audience: sts.amazonaws.com