name: "Nested Entrypoint - Terraform CI/CD"

"on":
  workflow_call:
    inputs:
      provider:
        description: "Cloud Provider: aws ou azure"
        required: true
        type: string
      environment:
        required: false
        type: string
        default: "dev"
      action:
        description: "apply ou destroy"
        required: false
        type: string
        default: "apply"
      aws-region:
        required: false
        type: string
        default: "us-east-1"
      working-directory:
        required: false
        type: string
        default: "infra"
      terraform-version:
        required: false
        type: string
        default: "1.9.0"

jobs:
  ci-terraform:
    name: "CI"
    uses: ./.github/workflows/engine-ci-terraform.yaml
    with:
      provider: ${{ inputs.provider }}
      environment: ${{ inputs.environment }}
      aws-region: ${{ inputs.aws-region }}
      working-directory: ${{ inputs.working-directory }}
      terraform-version: ${{ inputs.terraform-version }}
    secrets: inherit

  cd-terraform:
    name: "CD"
    needs: [ci-terraform]
    uses: ./.github/workflows/engine-cd-terraform.yaml
    with:
      provider: ${{ inputs.provider }}
      environment: ${{ inputs.environment }}
      action: ${{ inputs.action }}
      aws-region: ${{ inputs.aws-region }}
      working-directory: ${{ inputs.working-directory }}
      terraform-version: ${{ inputs.terraform-version }}
    secrets: inherit
