name: "Nested Entrypoint - Python CI/CD"

on:
  workflow_call:
    inputs:
      target-platform:
        description: "Destino do deploy: ecs, eks, lambda ou glue"
        required: true
        type: string
      app-name:
        required: true
        type: string
      environment:
        required: true
        type: string
        default: "dev"
      cluster-name:
        required: false
        type: string
        default: "default-cluster"  
        
jobs:
  quality-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: "${{ github.workspace }}/app"    
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run Lint & Tests
        run: |
          find . -type f -name requirements.txt -exec pip install -r {} \;
          pip install ruff pytest
          ruff check .
          pytest

  # Publish (ECR)
  publish-ecr:
    needs: quality-check
    if: inputs.target-platform == 'ecs'
    uses: kumabes-org/ci-cd-workflows/.github/workflows/engine-build-push-ecr.yaml@v1
    with:
      repository-name: ${{ inputs.app-name }}
      image-tag: ${{ github.sha }}
      aws-region: ${{ inputs.aws-region }}
    secrets: inherit

  # Deploy condicional para ECS
  deploy-ecs:
    needs: publish-ecr
    if: inputs.target-platform == 'ecs'
    uses: kumabes-org/ci-cd-workflows/.github/workflows/engine-deploy-ecs.yaml@v1
    with:
      cluster-name: "${{ inputs.cluster-name }}"
      service-name: "${{ inputs.app-name }}-${{ inputs.environment }}-svc"
      task-definition-family: "${{ inputs.app-name }}-${{ inputs.environment }}-tsk"
      container-name: "${{ inputs.app-name }}-${{ inputs.environment }}-ctr"
      image-uri: ${{ needs.publish-ecr.outputs.image-uri }}
    secrets: inherit

  # Deploy condicional para Lambda
  deploy-lambda:
    needs: quality-check
    if: inputs.target-platform == 'lambda'
    uses: kumabes-org/ci-cd-workflows/.github/workflows/engine-deploy-lambda.yaml@v1
    with:
      function-name: "${{ inputs.app-name }}-${{ inputs.environment }}-fn"
      package-type: "Zip"
    secrets: inherit

  # Deploy condicional para AWS Glue
  deploy-glue:
    needs: quality-check
    if: inputs.target-platform == 'glue'
    uses: kumabes-org/ci-cd-workflows/.github/workflows/engine-deploy-glue.yaml@v1
    with:
      job-name: "${{ inputs.app-name }}-${{ inputs.environment }}-etl"
      s3-bucket: "${{ inputs.app-name }}-${{ inputs.environment }}-etl"
      local-script-path: "src/etl/main.py"
    secrets: inherit